language: go
go:
- master

env:
  global:
      - CGO_ENABLED=0
      - CC_TEST_REPORTER_ID=30b34f215584a5f9ec0677996496d4ffb60567ddd88b73a41a0c167f262338c6

addons:
  artifacts: true
sudo: false
services:
 - docker

jobs:
  include:
    - stage: build
      script:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
      - go get github.com/axw/gocov/gocov
      - go get -u github.com/go-swagger/go-swagger/cmd/swagger
      - go test -coverprofile=c.out ./...
      - go build
      - swagger generate spec -m -o ./swagger.json
      - bin/docker_push.sh
      - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t gocov

    - stage: trigger downstream
      jdk: oraclejdk8
      script: |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        if [[ ($TRAVIS_BRANCH == master) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
           curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
           sh trigger-travis.sh weAutomateEverything bankHal $TRAVIS_ACCESS_TOKEN
        fi