apiVersion: v1
kind: ConfigMap
metadata:
  name: hal
  labels:
    name: hal
data:
  MONGO_SERVERS:
  MONGO_USER:
  MONGO_REPLICA_SET:
  MONGO_AUTH_SOURCE:
  MONGO_SSL:
  NO_PROXY:
  SNMP_SERVER:
  SNMP_PORT:
  CALLOUT_URL:
  JIRA_TEMPLATE:
  JIRA_DEFAULT_USER:
  SKYNET_URL:
  SKYNET_USER:
---
kind: Service
apiVersion: v1
metadata:
  name: hal
spec:
  selector:
    app: hal
  ports:
  - protocol: TCP
    name: snmp
    port: 161
    targetPort: 9162
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8000
  - protocol: TCP
    name: grpc
    port: 8080
    targetPort: 8080
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: hal
  annotations:
   kubernetes.io/ingress.class: istio
spec:
   rules:
     - host:
       http:
         paths:
           - backend:
               serviceName: hal
               servicePort: http
